### ISSUE TITLE
A package for Turkish

### ISSUE THREAD

**Issue by maidis** [martonmiklos/unofficial-jolla-translation#10]
It's not directly related to this repo, but it is one of the easiest ways to communicate with you. Could you make a package for Turkish.

**Comment by martonmiklos** [comment]
Sure, here you go:
https://openrepos.net/content/martonmiklos/turkish-community-translation-jolla

Let me know if anything is not 100%-ly correct somewhere. 
If you have finished the translation it might make sense to run an automated spellcheck. For details see here:

https://together.jolla.com/question/170936/reminder-for-promoting-finished-translations-to-official-release/

(There are going to be a bunch of false positives.)

**Comment by maidis** [comment]
It gives a 14K lines output. It's really hard to find real problems from such a long output. But I caught a problem from your screenshots: Ambiences must be Ambiyanslar. Currently translate.sailfishos.org seems to be down. I'm going to check it later.
