### ISSUE TITLE
Missing translation package

### ISSUE THREAD

**Issue by peremen** [martonmiklos/unofficial-jolla-translation#11]
I don't know when it was exactly added, but current tools/packagelist.txt lacks one package available on pootle.

```
diff --git a/tools/packagelist.txt b/tools/packagelist.txt
index 1a81ca7..90549b8 100644
--- a/tools/packagelist.txt
+++ b/tools/packagelist.txt
@@ -41,6 +41,7 @@ contactsd/contactsd.ts
 jolla-email/jolla-email.ts
 jolla-alarm-ui/alarm-ui.ts
 jolla-calendar/calendar.ts
+jolla-calendar/sailfish-components-calendar-qt5.ts
 sailfish-maps/sailfish-maps.ts
 eventsview-extensions/eventsview-extensions-social.ts
 eventsview-extensions/lipstick-jolla-home-facebook.ts
```

**Comment by martonmiklos** [comment]
Hey,

I have not been able to find this package on the translate.sailfishos.org now.
Google cache seems to remember to it:
http://bit.ly/2iVN4LV

Also there are untranslated strings in this area as well with the 100%ly finished translations too.

@sledges  do you have any information about this?
Thanks in advance!

**Comment by peremen** [comment]
I also suggest to alphabetically sort tools/packagelist.txt for better maintainability, as newer Sailfish OS release can carry extra message catalogs.

**Comment by martonmiklos** [comment]
That's a good point, thanks for bringing it up.
I would be still curious how and when you found the sailfish-components-calendar-qt5 package?
Is it suddenly disappeared?

**Comment by peremen** [comment]
I can see it today. This is not a single package, another message catalog inside jolla-calendar. You can find that .ts file there.

**Comment by martonmiklos** [comment]
Auch. I have missed the point that it is under an already added entity. Thanks for bringing this up, hopefully it will solve the issues with the untranslated strings in the calendar view.
