### ISSUE TITLE
Package for Azerbaijani

### ISSUE THREAD

**Issue by Khazarli** [martonmiklos/unofficial-jolla-translation#19]
Hey there, could you please assembly test translation package for Azerbaijani? Thank you in any case

**Comment by martonmiklos** [comment]
Hey @Khazarli 

What ICU code do you prefer?
See here:
https://www.localeplanet.com/icu/

**Comment by Khazarli** [comment]
@martonmiklos probably the one that says "az" or "az_Latn" in case if there would be cyrillyc in future

**Comment by martonmiklos** [comment]
Here you go:
https://www.dropbox.com/s/skqrp9qb6jvrc40/unofficial-jolla-language-pack-az-4.4.0.58-0.0.2.noarch.rpm?dl=0

**Comment by Khazarli** [comment]
Thankies! Gonna test it now

**Comment by Khazarli** [comment]
I'm sorry to bother you, I've made a little bit mistake...
I've translated one app and used "az" as Azerbaijani indicator.

Could you please reassembly it with just "az" ICU code? And please, name it "Azərbaycanca" instead of "Azerbaijani" if it's possible. Thanks a lot!

**Comment by martonmiklos** [comment]
Freshly from the owen:
https://www.dropbox.com/s/22s1ntizpv5uvww/unofficial-jolla-language-pack-az-4.4.0.58-0.0.3.noarch.rpm?dl=0
