### ISSUE TITLE
createqm.sh and nonexistent /usr/share/translations folder

### ISSUE THREAD

**Issue by maidis** [martonmiklos/unofficial-jolla-translation#8]
Thanks for this useful tool. I'm just starting to use it. 

When I run createqm.sh script, it gives:

```
lrelease error: Parse error at translations/tr/csd/csd.ts:1:0: Premature end of document.
Updating 'usr/share/translations/clock-tr.qm'...
```
It would be nice to create this folder on the first run if it doesn't exist already with mkdir -p or some other ways.

**Comment by martonmiklos** [comment]
Thanks for the feedback, I have fixed this.
Let me know if you need any help with the translation packaging.
