### ISSUE TITLE
Some files for Turkish package support

### ISSUE THREAD

**Issue by maidis** [martonmiklos/unofficial-jolla-translation#9]
Sorry no PR this time. If it is suitable for you, could you add the following files:

**unofficial-jolla-language-pack-tr.spec**

```
#make sure change these variables to suit your language
%define CONFLANG tr
%define LOCNAME tr_TR
%define RPM_SUFFIX tr
%define QM_SUFFIX tr

Name: unofficial-jolla-language-pack-%{CONFLANG}
Version:	2.1.0
Release:	0.0.1
Summary:	Resmi Olmayan Türkçe Dil Paketi

Group: Qt/Qt
License: GPL
URL: https://translate.sailfishos.org/tr
Source0: %{name}.tar.bz2
BuildArch: noarch
BuildRoot: /var/tmp/%{name}-%{version}-XXXXXX
Packager: Miklós Márton

%include rpm/common.inc

%changelog
* Wed Feb 08 2017 Miklos Marton <martonmiklosqdev@gmail.com> 2.1.0-0.0.1
- First release

```

**tr.conf**

```
Name=Türkçe
LocaleCode=tr_TR.utf8
Region=
RegionLabel=Region: %1
```

**tr.png**
https://www.dropbox.com/s/dv9jjdny70karh4/tr.png?dl=0

**README.md**
```
...
export POOTLE_LANG=tr; ./tools/fetchts.sh # this will take a while because it downloads the ts files from Pootle
export POOTLE_LANG=tr; export QM_SUFFIX=tr; ./tools/createqm.sh 
export LANGCODE=tr; ./tools/createrpm.sh
...
```

**Comment by martonmiklos** [comment]
Hi,

Thanks for the files, I have added them to the repository. 

Should I publish the package to the openrepos?

**Comment by maidis** [comment]
Thank you so much. I've just started to help Turkish translation. Translation rate is only 12% now. I plan to make a 100% translation rate in about a month. Would it be better to wait a month and then publish it? Then I can open a new request or contact you in another way.

**Comment by martonmiklos** [comment]
Ah that makes sense. Let me know if you are ready!
